FROM golang:1.19 as build-stage

WORKDIR /app

COPY .. .

RUN CGO_ENABLED=0 GOOS=linux go build -mod vendor -o bin/docker-plugin cmd/sidecars/docker/main.go


# Deploy the application binary into a lean image
FROM docker AS build-release-stage

WORKDIR /

COPY --from=build-stage /app/bin/docker-plugin /docker-plugin

USER nonroot:nonroot

ENTRYPOINT ["/docker-plugin"]