InterlinkURL: "http://localhost"
SidecarURL: "http://localhost"
InterlinkPort: "3000"
SidecarService: "slurm" #docker, slurm
CommandPrefix: ""
Tsocks: false
TsocksPath: "$WORK/tsocks-1.8beta5+ds1/libtsocks.so"
TsocksLoginNode: "login01"